### PR TITLE
Add header image and TOC to README.md

### PR DESCRIPTION
**Pull request by SatjaSivcev**

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
Can someone help me with the error CI is reporting?

**Comment by eskaurz** [comment]
> Can someone help me with the error CI is reporting?

Interesting.. 
First of all, it has nothing to do with your change, because the nightly scheduled master build has also been failing for some days. Same with zivid-python. I suspect that pip finally dropped support for Python 3.5. Anyway, we'll have to find some solution for zivid-python right away, and I'll let you know when we have something.

**Comment by eskaur** [comment]
CI fix is merged, so should be fine if you rebase. @SatjaSivcev

**Comment by SatjaSivcev** [comment]
Can you approve again?

**Comment by eskaur** [comment]
> Can you approve again?

I never approved it ;)
Anyway, I can have a look now.

**Review by eskaur — APPROVED** [review]

**Pull request merged**
